# Generated by Django 3.0.6 on 2020-09-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0003_auto_20200930_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
