# Generated by Django 3.0.6 on 2020-09-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0005_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
