# Generated by Django 3.0.6 on 2020-09-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0007_image_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
