# Generated by Django 3.0.6 on 2020-10-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0008_auto_20201001_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('des', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
