# Generated by Django 3.0.6 on 2020-10-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0009_auto_20201001_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='title',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
