# Generated by Django 3.0.6 on 2020-10-01 09:49

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0010_detail_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='vid',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
