# Generated by Django 3.0.6 on 2020-10-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0011_detail_vid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='vid',
        ),
        migrations.AddField(
            model_name='detail',
            name='intid',
            field=models.IntegerField(null=True),
        ),
    ]
