# Generated by Django 3.0.6 on 2020-10-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0013_auto_20201007_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
