# Generated by Django 3.0.6 on 2020-10-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0014_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='subtitle',
            field=models.FileField(null=True, upload_to='subtitle'),
        ),
    ]
