# Generated by Django 3.0.6 on 2020-10-13 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vid', '0017_auto_20201011_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
