# Generated by Django 3.0.6 on 2020-10-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0018_detail_likers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='subtitle',
        ),
    ]
