# Generated by Django 3.0.6 on 2020-10-16 05:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vid', '0019_remove_detail_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='reporters',
            field=models.ManyToManyField(blank=True, related_name='reporters', to=settings.AUTH_USER_MODEL),
        ),
    ]
