# Generated by Django 3.0.6 on 2020-10-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0020_detail_reporters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='reporters',
        ),
    ]
